spring:
  thymeleaf:
    mode: HTML
  datasource:
    url: jdbc:mysql://localhost:3306/stock_admin?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 80
pagehelper:
  helper-dialect: mysql
logging:
  config: classpath:logging/logback-spring.xml
log:
  info:
    path: /app/stock_admin_logs/stock-admin/info/stock_admin-info
  error:
    path: /app/stock_admin_logs/stock-admin/error/stock_admin-error
